variable "instance_name" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "security_groups_name" {}
variable "username" {}
variable "private_key_path" {}
variable "ami" {}
variable "key_name" {}