services:
  pgadmin4:
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hrubechhombessa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    image: dpage/pgadmin4
    container_name: pgadmin